-- ============================================================
-- Sample leave requests for the test accounts.
-- Run AFTER creating the two auth users (see README → Test accounts),
-- which will auto-create their `profiles` rows via the trigger.
-- Replace the employee_id below with the real UUID from `profiles`
-- for employee@test.com (Supabase Dashboard → Authentication → Users).
-- ============================================================

-- Example:
-- insert into leave_requests (employee_id, start_date, end_date, reason, status)
-- values
--   ('<employee-uuid>', current_date + 7, current_date + 9, 'Family trip', 'pending'),
--   ('<employee-uuid>', current_date - 20, current_date - 18, 'Doctor appointment', 'approved'),
--   ('<employee-uuid>', current_date - 40, current_date - 39, 'Personal matter', 'rejected');
